#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

  cookbook 'apt'
  cookbook 'nginx',
    :git => "https://github.com/bitcellar-labs/nginx",
    :ref => "features/prebuilt-passenger"
  cookbook 'rvm'
  cookbook 'build-essential'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
