#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

  cookbook 'apt'

  # Using bitcellars nginx fork which includes support for
  # the precompiled passenger-nginx binaries.
  cookbook 'nginx',
    :git => "https://github.com/bitcellar-labs/nginx",
    :ref => "features/prebuilt-passenger"

  cookbook 'rvm'

  cookbook 'redisio', '~> 2.2.4'

  cookbook 'postgresql', '~> 3.4.12'
